name: Release Beta
on:
  push:
    branches:
      - beta
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'
      - '!.github/workflows/beta.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  test_and_release:
    name: "Test and release if needed"
    runs-on: ubuntu-latest
    outputs:
      has-updated: ${{ steps.version-updated.outputs.has-updated }}
      current-version: ${{ steps.version-updated.outputs.current-package-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
   
      - name: Install
        run: npm ci
        
      - name: Typecheck
        run: npm run typecheck
     
      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      
      - name: Check if publish is needed
        uses: JiPaix/package-json-updated-action@v1.0.5
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last published version
        if: steps.version-updated.outputs.has-updated
        id: tag
        run: echo "last-tag=$(git describe --tags --abbrev=0 --match "*-beta" ${{github.ref}})" >> $GITHUB_OUTPUT
  
      - name: Set target version
        if: steps.version-updated.outputs.has-updated
        id: version
        run: echo "build-version=${{steps.version-updated.outputs.current-package-version}}-beta" >> $GITHUB_OUTPUT

      - name: Generate release notes
        if: steps.version-updated.outputs.has-updated
        uses: ./.github/actions/release-notes
        id: release-note
        with:
          from: ${{ steps.tag.outputs.last-tag }}
          to: ${{ github.ref }}
          include-commit-body: true
          include-abbreviated-commit: true

      - name: Delete outdated drafts
        if: steps.version-updated.outputs.has-updated
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare artifacts
        if: steps.version-updated.outputs.has-updated
        run: npm run start -- v${{ steps.version.outputs.build-version }}

      - name: Create Release
        if: steps.version-updated.outputs.has-updated
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          artifacts: "dist/*.js,dist/*.json,dist/*.svg,dist/*.png,dist/*.jpg,dist/*.webp"
          tag: v${{ steps.version.outputs.build-version }}
          name: v${{ steps.version.outputs.build-version }}
          body: ${{ steps.release-note.outputs.release-note }}
